---
run:
  timeout: 5m

linters:
  enable-all: true
  disable:
    - tagliatelle
    - nonamedreturns
    - exhaustivestruct
    - exhaustruct

    # deprecated
    - nosnakecase
    - scopelint
    - maligned
    - exhaustivestruct
    - interfacer
    - golint
    - structcheck
    - ifshort
    - deadcode
    - varcheck