---
name: test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.*
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test
        # env:
        #   ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic -p=1 ./...

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
